/* This file is autogenerated by jig 0.3.0 from file mp4h-njs.jsi
 *
 * DO NOT EDIT THIS FILE */

#include <njs/jig.h>
#include "mp4h-njs.h"

#line 6 "mp4h-njs.jsi"
/* 
 * mp4h extension for NJS
 * Copyright (c) 2001 Anders Dinsen
 *
 * Author: Anders Dinsen <anders@dinsen.net>
 */

/*
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 59 Temple Place - Suite 330, Boston,
 * MA 02111-1307, USA
 */

/*
 * $Source: /cvsroot/mp4h/mp4h/modules/javascript/mp4h-njs.c,v $
 * $Id: mp4h-njs.c,v 1.1 2002/07/01 22:12:26 barbier Exp $
 */

#line 38 "mp4h-njs.c"

static int MP4H_method(JSVirtualMachine *js_vm, JSBuiltinInfo *js_info, void *js_ictx, JSSymbol js_method, JSNode *js_retval, JSNode *js_args) {
  MP4HCtx *js_context = js_info->obj_context;

  if(js_ictx == NULL) {
  if(js_method == js_context->s_use) {
#undef js_return
#define js_return js_return_undef

  char *package = NULL;
  JSNode js_tempnode;
  if (js_args->u.vinteger != 1) {
    js_vm_set_err(js_vm, "use(): illegal number of arguments");
    js_vm_error(js_vm);
  }
  js_vm_to_string(js_vm, &js_args[1], &js_tempnode);
  package = js_string_to_c_string(js_vm, &js_tempnode);
    do {
#line 87 "mp4h-njs.jsi"
    /* TODO */
  
#line 60 "mp4h-njs.c"
    } while(0);
  js_free(package);
  } else if(js_method == js_context->s_loadModule) {
#undef js_return
#define js_return js_return_undef

  char *module = NULL;
  JSNode js_tempnode;
  if (js_args->u.vinteger != 1) {
    js_vm_set_err(js_vm, "loadModule(): illegal number of arguments");
    js_vm_error(js_vm);
  }
  js_vm_to_string(js_vm, &js_args[1], &js_tempnode);
  module = js_string_to_c_string(js_vm, &js_tempnode);
    do {
#line 96 "mp4h-njs.jsi"
    /* TODO */
  
#line 79 "mp4h-njs.c"
    } while(0);
  js_free(module);
  } else if(js_method == js_context->s_setQuotes) {
#undef js_return
#define js_return js_return_undef

  char *left = NULL;
  char *right = NULL;
  unsigned int visible = 0;
  JSNode js_tempnode;
  if (js_args->u.vinteger != 3) {
    js_vm_set_err(js_vm, "setQuotes(): illegal number of arguments");
    js_vm_error(js_vm);
  }
  js_vm_to_string(js_vm, &js_args[1], &js_tempnode);
  left = js_string_to_c_string(js_vm, &js_tempnode);
  js_vm_to_string(js_vm, &js_args[2], &js_tempnode);
  right = js_string_to_c_string(js_vm, &js_tempnode);
  visible = js_vm_to_boolean(js_vm, &js_args[3]);
    do {
#line 108 "mp4h-njs.jsi"
    /* TODO */
  
#line 103 "mp4h-njs.c"
    } while(0);
  js_free(left);
  js_free(right);
  } else if(js_method == js_context->s_warning) {
#undef js_return
#define js_return js_return_undef

  char *message = NULL;
  JSNode js_tempnode;
  if (js_args->u.vinteger != 1) {
    js_vm_set_err(js_vm, "warning(): illegal number of arguments");
    js_vm_error(js_vm);
  }
  js_vm_to_string(js_vm, &js_args[1], &js_tempnode);
  message = js_string_to_c_string(js_vm, &js_tempnode);
    do {
#line 118 "mp4h-njs.jsi"
    /* TODO */
  
#line 123 "mp4h-njs.c"
    } while(0);
  js_free(message);
  } else if(js_method == js_context->s_exit) {
#undef js_return
#define js_return js_return_undef

  long status = 0;
  char *message = NULL;
  JSNode js_tempnode;
  if (js_args->u.vinteger != 2) {
    js_vm_set_err(js_vm, "exit(): illegal number of arguments");
    js_vm_error(js_vm);
  }
  js_vm_to_number(js_vm, &js_args[1], &js_tempnode);
  if(js_tempnode.type == JS_INTEGER) {
    status = js_tempnode.u.vinteger;
  } else {
    js_vm_set_err(js_vm, "exit(): illegal argument (status not an integer)");
    js_vm_error(js_vm);
  }
  js_vm_to_string(js_vm, &js_args[2], &js_tempnode);
  message = js_string_to_c_string(js_vm, &js_tempnode);
    do {
#line 128 "mp4h-njs.jsi"
    /* TODO */
  
#line 150 "mp4h-njs.c"
    } while(0);
  js_free(message);
  } else if(js_method == js_context->s_atEndOfFile) {
#undef js_return
#define js_return js_return_undef

  char *text = NULL;
  JSNode js_tempnode;
  if (js_args->u.vinteger != 1) {
    js_vm_set_err(js_vm, "atEndOfFile(): illegal number of arguments");
    js_vm_error(js_vm);
  }
  js_vm_to_string(js_vm, &js_args[1], &js_tempnode);
  text = js_string_to_c_string(js_vm, &js_tempnode);
    do {
#line 137 "mp4h-njs.jsi"
    /* TODO */
  
#line 169 "mp4h-njs.c"
    } while(0);
  js_free(text);
  } else if(js_method == js_context->s_getVar) {
#undef js_return
#define js_return js_return_cstring

  char *name = NULL;
  JSNode js_tempnode;
  if (js_args->u.vinteger != 1) {
    js_vm_set_err(js_vm, "getVar(): illegal number of arguments");
    js_vm_error(js_vm);
  }
  js_vm_to_string(js_vm, &js_args[1], &js_tempnode);
  name = js_string_to_c_string(js_vm, &js_tempnode);
    do {
#line 147 "mp4h-njs.jsi"
    /* TODO */
  
#line 188 "mp4h-njs.c"
    } while(0);
  js_free(name);
  } else if(js_method == js_context->s_setVar) {
#undef js_return
#define js_return js_return_undef

  char *name = NULL;
  char *value = NULL;
  JSNode js_tempnode;
  if (js_args->u.vinteger != 2) {
    js_vm_set_err(js_vm, "setVar(): illegal number of arguments");
    js_vm_error(js_vm);
  }
  js_vm_to_string(js_vm, &js_args[1], &js_tempnode);
  name = js_string_to_c_string(js_vm, &js_tempnode);
  js_vm_to_string(js_vm, &js_args[2], &js_tempnode);
  value = js_string_to_c_string(js_vm, &js_tempnode);
    do {
#line 157 "mp4h-njs.jsi"
    /* TODO */
  
#line 210 "mp4h-njs.c"
    } while(0);
  js_free(name);
  js_free(value);
  } else if(js_method == js_context->s_varExists) {
#undef js_return
#define js_return js_return_boolean

  char *name = NULL;
  JSNode js_tempnode;
  if (js_args->u.vinteger != 1) {
    js_vm_set_err(js_vm, "varExists(): illegal number of arguments");
    js_vm_error(js_vm);
  }
  js_vm_to_string(js_vm, &js_args[1], &js_tempnode);
  name = js_string_to_c_string(js_vm, &js_tempnode);
    do {
#line 166 "mp4h-njs.jsi"
    /* TODO */
  
#line 230 "mp4h-njs.c"
    } while(0);
  js_free(name);
  } else if(js_method == js_context->s_defineUserTag) {
#undef js_return
#define js_return js_return_undef

  char *name = NULL;
  char *definition = NULL;
  unsigned int verbatimAttributes = 0;
  unsigned int container = 0;
  unsigned int deleteWhitespace = 0;
  JSNode js_tempnode;
  if (js_args->u.vinteger != 5) {
    js_vm_set_err(js_vm, "defineUserTag(): illegal number of arguments");
    js_vm_error(js_vm);
  }
  js_vm_to_string(js_vm, &js_args[1], &js_tempnode);
  name = js_string_to_c_string(js_vm, &js_tempnode);
  js_vm_to_string(js_vm, &js_args[2], &js_tempnode);
  definition = js_string_to_c_string(js_vm, &js_tempnode);
  verbatimAttributes = js_vm_to_boolean(js_vm, &js_args[3]);
  container = js_vm_to_boolean(js_vm, &js_args[4]);
  deleteWhitespace = js_vm_to_boolean(js_vm, &js_args[5]);
    do {
#line 193 "mp4h-njs.jsi"
    /* TODO */
  
#line 258 "mp4h-njs.c"
    } while(0);
  js_free(name);
  js_free(definition);
  } else if(js_method == js_context->s_divert) {
#undef js_return
#define js_return js_return_undef

  long divnum = 0;
  JSNode js_tempnode;
  if (js_args->u.vinteger != 1) {
    js_vm_set_err(js_vm, "divert(): illegal number of arguments");
    js_vm_error(js_vm);
  }
  js_vm_to_number(js_vm, &js_args[1], &js_tempnode);
  if(js_tempnode.type == JS_INTEGER) {
    divnum = js_tempnode.u.vinteger;
  } else {
    js_vm_set_err(js_vm, "divert(): illegal argument (divnum not an integer)");
    js_vm_error(js_vm);
  }
    do {
#line 203 "mp4h-njs.jsi"
    /* TODO */
  
#line 283 "mp4h-njs.c"
    } while(0);
  } else if(js_method == js_context->s_undivert) {
#undef js_return
#define js_return js_return_undef

  long divnum = 0;
  JSNode js_tempnode;
  if (js_args->u.vinteger != 1) {
    js_vm_set_err(js_vm, "undivert(): illegal number of arguments");
    js_vm_error(js_vm);
  }
  js_vm_to_number(js_vm, &js_args[1], &js_tempnode);
  if(js_tempnode.type == JS_INTEGER) {
    divnum = js_tempnode.u.vinteger;
  } else {
    js_vm_set_err(js_vm, "undivert(): illegal argument (divnum not an integer)");
    js_vm_error(js_vm);
  }
    do {
#line 213 "mp4h-njs.jsi"
    /* TODO */
  
#line 306 "mp4h-njs.c"
    } while(0);
  } else if(js_method == js_context->s_divnum) {
#undef js_return
#define js_return js_return_int

  if (js_args->u.vinteger != 0) {
    js_vm_set_err(js_vm, "divnum(): illegal number of arguments");
    js_vm_error(js_vm);
  }
    do {
#line 220 "mp4h-njs.jsi"
    /* TODO */
  
#line 320 "mp4h-njs.c"
    } while(0);
  } else 
    return JS_PROPERTY_UNKNOWN;

  return JS_PROPERTY_FOUND;
  }

  
    return JS_PROPERTY_UNKNOWN;

js_done:
  return JS_PROPERTY_FOUND;
}

static int MP4H_property(JSVirtualMachine *js_vm, JSBuiltinInfo *js_info, void *js_ictx, JSSymbol js_property, int js_op, JSNode *js_retval) {
  MP4HCtx *js_context = js_info->obj_context;

  if(js_ictx == NULL) {
  if(js_property == js_context->s_LQUOTE) {
    if(js_op == JS_BUILTIN_PROP_SET) {
      js_vm_set_err(js_vm, "LQUOTE: read-only property");
      js_vm_error(js_vm);
    }
    else if(js_op == JS_BUILTIN_PROP_DELETE) {
      js_vm_set_err(js_vm, "LQUOTE: undeletable property");
      js_vm_error(js_vm);
    }
    else {
#undef js_return
#define js_return js_return_cstring

#line 54 "mp4h-njs.jsi"
      /* TODO */
    
#line 355 "mp4h-njs.c"
    }
  } else if(js_property == js_context->s_RQUOTE) {
    if(js_op == JS_BUILTIN_PROP_SET) {
      js_vm_set_err(js_vm, "RQUOTE: read-only property");
      js_vm_error(js_vm);
    }
    else if(js_op == JS_BUILTIN_PROP_DELETE) {
      js_vm_set_err(js_vm, "RQUOTE: undeletable property");
      js_vm_error(js_vm);
    }
    else {
#undef js_return
#define js_return js_return_cstring

#line 67 "mp4h-njs.jsi"
      /* TODO */
    
#line 373 "mp4h-njs.c"
    }
  } else 
    return JS_PROPERTY_UNKNOWN;

  return JS_PROPERTY_FOUND;
  }

  
    return JS_PROPERTY_UNKNOWN;

js_done:
  return JS_PROPERTY_FOUND;
}

static int MP4H_query(JSVirtualMachine *js_vm, JSBuiltinInfo *js_info, void *js_ictx, JSSymbol js_symbol) {
  MP4HCtx *js_context = js_info->obj_context;

  if(js_ictx == NULL) {
    if(js_symbol == js_context->s_LQUOTE) return JS_PROPERTY_FOUND;
    else if(js_symbol == js_context->s_RQUOTE) return JS_PROPERTY_FOUND;
    else if(js_symbol == js_context->s_use) return JS_PROPERTY_FOUND;
    else if(js_symbol == js_context->s_loadModule) return JS_PROPERTY_FOUND;
    else if(js_symbol == js_context->s_setQuotes) return JS_PROPERTY_FOUND;
    else if(js_symbol == js_context->s_warning) return JS_PROPERTY_FOUND;
    else if(js_symbol == js_context->s_exit) return JS_PROPERTY_FOUND;
    else if(js_symbol == js_context->s_atEndOfFile) return JS_PROPERTY_FOUND;
    else if(js_symbol == js_context->s_getVar) return JS_PROPERTY_FOUND;
    else if(js_symbol == js_context->s_setVar) return JS_PROPERTY_FOUND;
    else if(js_symbol == js_context->s_varExists) return JS_PROPERTY_FOUND;
    else if(js_symbol == js_context->s_defineUserTag) return JS_PROPERTY_FOUND;
    else if(js_symbol == js_context->s_divert) return JS_PROPERTY_FOUND;
    else if(js_symbol == js_context->s_undivert) return JS_PROPERTY_FOUND;
    else if(js_symbol == js_context->s_divnum) return JS_PROPERTY_FOUND;
    else return JS_PROPERTY_UNKNOWN;
  }

  return JS_PROPERTY_UNKNOWN;
}

static int MP4H_enumerate(JSVirtualMachine *js_vm, JSBuiltinInfo *js_info, void *js_ictx, int js_nth, JSNode *js_retval) {
  if(js_ictx == NULL) {
    switch(js_nth) {
      case 0:
        js_vm_make_static_string(js_vm, js_retval, "LQUOTE", 6);
        return 1;
      case 1:
        js_vm_make_static_string(js_vm, js_retval, "RQUOTE", 6);
        return 1;
      default:
        return js_vm_object_nth (js_vm, js_info->prototype, js_nth - 2, js_retval);
    }
  }

  switch(js_nth) {
    default:
      return js_vm_object_nth (js_vm, js_retval->u.vbuiltin->prototype, js_nth - 0, js_retval);
  }
}

void mp4h_MP4H(JSVirtualMachine *js_vm) {
  JSNode *js_node;
  JSBuiltinInfo *js_info;
  MP4HCtx *MP4Hctx;

  MP4Hctx = js_calloc(js_vm, 1, sizeof(*MP4Hctx));
  MP4Hctx->s_LQUOTE = js_vm_intern(js_vm, "LQUOTE");
  MP4Hctx->s_RQUOTE = js_vm_intern(js_vm, "RQUOTE");
  MP4Hctx->s_use = js_vm_intern(js_vm, "use");
  MP4Hctx->s_loadModule = js_vm_intern(js_vm, "loadModule");
  MP4Hctx->s_setQuotes = js_vm_intern(js_vm, "setQuotes");
  MP4Hctx->s_warning = js_vm_intern(js_vm, "warning");
  MP4Hctx->s_exit = js_vm_intern(js_vm, "exit");
  MP4Hctx->s_atEndOfFile = js_vm_intern(js_vm, "atEndOfFile");
  MP4Hctx->s_getVar = js_vm_intern(js_vm, "getVar");
  MP4Hctx->s_setVar = js_vm_intern(js_vm, "setVar");
  MP4Hctx->s_varExists = js_vm_intern(js_vm, "varExists");
  MP4Hctx->s_defineUserTag = js_vm_intern(js_vm, "defineUserTag");
  MP4Hctx->s_divert = js_vm_intern(js_vm, "divert");
  MP4Hctx->s_undivert = js_vm_intern(js_vm, "undivert");
  MP4Hctx->s_divnum = js_vm_intern(js_vm, "divnum");
  js_info = js_vm_builtin_info_create(js_vm);
  js_info->method_proc = MP4H_method;
  js_info->property_proc = MP4H_property;
  js_info->query_proc = MP4H_query;
  js_info->enumerate_proc = MP4H_enumerate;
  js_info->obj_context = MP4Hctx;
  js_info->obj_context_delete = js_free;
  js_node = &js_vm->globals[js_vm_intern(js_vm, "MP4H")];
  js_vm_builtin_create(js_vm, js_node, js_info, NULL);
  do {
#line 77 "mp4h-njs.jsi"
    /* TODO */
  
/* #line unknown "mp4h-njs.c" */
  } while(0);
  return;
}
