/* This file is autogenerated by jig 0.3.0 from file mp4h-njs.jsi
 *
 * DO NOT EDIT THIS FILE */

#include <njs/internal.h>

#line 2 "mp4h-njs.jsi"
#include "mp4h.h"

#line 10 "mp4h-njs.h"
typedef struct {
  JSSymbol s_LQUOTE;
  JSSymbol s_RQUOTE;
  JSSymbol s_use;
  JSSymbol s_loadModule;
  JSSymbol s_setQuotes;
  JSSymbol s_warning;
  JSSymbol s_exit;
  JSSymbol s_atEndOfFile;
  JSSymbol s_getVar;
  JSSymbol s_setVar;
  JSSymbol s_varExists;
  JSSymbol s_defineUserTag;
  JSSymbol s_divert;
  JSSymbol s_undivert;
  JSSymbol s_divnum;
} MP4HCtx;

void mp4h_MP4H(JSVirtualMachine *js_vm);

